DROP TABLE IF EXISTS STOCKS;

CREATE TABLE STOCKS (
TICKER VARCHAR(250) PRIMARY KEY NOT NULL,
TYPE VARCHAR(2) NOT NULL,
QTY INT NOT NULL,
PRICE NUMERIC(20, 2) DEFAULT NULL,
POSITION INT NOT NULL,
EXP_RET DECIMAL DEFAULT NULL,
STD_DEV DECIMAL DEFAULT NULL
);

DROP TABLE IF EXISTS "OPTIONS";

CREATE TABLE "OPTIONS" (
TICKER VARCHAR(250) PRIMARY KEY NOT NULL,
TYPE VARCHAR(2) NOT NULL,
QTY INT NOT NULL,
PRICE NUMERIC(20, 2) DEFAULT NULL,
POSITION INT NOT NULL,
TIME_TO_MAT DECIMAL DEFAULT NULL,
STRIKE_PRICE NUMERIC(20, 2) DEFAULT NULL,
STD_DEV DECIMAL DEFAULT NULL
);


