DROP TABLE IF EXISTS STOCKS;

CREATE TABLE STOCKS (
TICKER VARCHAR(250) PRIMARY KEY NOT NULL,
TYPE VARCHAR(2) NOT NULL,
QTY INT NOT NULL,
PRICE NUMERIC(20, 2) DEFAULT NOT NULL,
POSITION INT NOT NULL,
MU DECIMAL DEFAULT NOT NULL,
SIGMA DECIMAL DEFAULT NOT NULL
);

DROP TABLE IF EXISTS "OPTIONS";

CREATE TABLE "OPTIONS" (
TICKER VARCHAR(250) PRIMARY KEY NOT NULL,
TYPE VARCHAR(2) NOT NULL,
QTY INT NOT NULL,
PRICE NUMERIC(20, 2) DEFAULT NOT NULL,
POSITION INT NOT NULL,
TTM DECIMAL DEFAULT NOT NULL,
STRIKE_PRICE NUMERIC(20, 2) DEFAULT NOT NULL,
SIGMA DECIMAL DEFAULT NOT NULL
);


